export const styles = {
  root: {
    fontFamily: "'Libre Franklin', sans-serif",
    color: "var(--text)",
    background: "var(--bg)",
    minHeight: "100vh",
    position: "relative",
  },

  // Header
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 28px",
    borderBottom: "1px solid var(--border)",
    background: "rgba(250, 246, 240, 0.88)",
    backdropFilter: "blur(16px) saturate(150%)",
    WebkitBackdropFilter: "blur(16px) saturate(150%)",
    position: "sticky",
    top: 0,
    zIndex: 50,
  },
  logoRow: { display: "flex", alignItems: "center", gap: 16 },
  logo: { display: "flex", alignItems: "center", gap: 10 },
  logoIcon: {
    width: 30,
    height: 30,
    borderRadius: "50%",
    background: "linear-gradient(135deg, #ddb892, #c9a690)",
    display: "inline-block",
  },
  logoText: {
    fontFamily: "'Playfair Display', serif",
    fontWeight: 700,
    fontSize: 17,
    letterSpacing: "-0.02em",
    color: "var(--text)",
  },
  tagline: {
    fontSize: 12,
    color: "var(--text-light)",
    borderLeft: "1px solid var(--border)",
    paddingLeft: 16,
    fontWeight: 500,
    letterSpacing: "0.04em",
  },
  headerRight: { display: "flex", alignItems: "center", gap: 12 },
  badge: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    color: "var(--accent-warm)",
    background: "rgba(160, 103, 75, 0.08)",
    padding: "5px 12px",
    borderRadius: 20,
    border: "1px solid rgba(160, 103, 75, 0.12)",
  },

  // Trending
  trendingBar: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 28px",
    background: "var(--surface-2)",
    borderBottom: "1px solid var(--border)",
    overflow: "hidden",
    whiteSpace: "nowrap",
    fontSize: 12,
  },
  trendingLabel: {
    fontWeight: 700,
    fontSize: 10,
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    color: "var(--accent-warm)",
    flexShrink: 0,
  },
  trendingItem: { color: "var(--text-muted)", fontWeight: 400 },
  trendingDot: { color: "var(--sand)", fontSize: 16 },

  // Layout
  mainLayout: {
    display: "flex",
    gap: 0,
    minHeight: "calc(100vh - 100px)",
  },
  catalogPanel: {
    flex: 1,
    padding: "24px 28px",
    overflowY: "auto",
  },

  // Search
  searchWrapper: {
    position: "relative",
    marginBottom: 20,
  },
  searchInput: {
    width: "100%",
    padding: "14px 18px 14px 44px",
    background: "var(--surface)",
    borderWidth: 1.5,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 28,
    color: "var(--text)",
    fontSize: 14,
    fontFamily: "'Libre Franklin', sans-serif",
    fontWeight: 400,
    transition: "all 0.3s ease",
    boxShadow: "0 2px 12px rgba(180, 140, 100, 0.04)",
  },

  // Tabs
  tabsRow: {
    display: "flex",
    gap: 6,
    marginBottom: 20,
    flexWrap: "wrap",
  },
  tab: {
    padding: "7px 16px",
    borderRadius: 20,
    background: "transparent",
    borderWidth: 1.5,
    borderStyle: "solid",
    borderColor: "rgba(180, 160, 140, 0.18)",
    color: "var(--text-muted)",
    fontSize: 12,
    fontWeight: 600,
    fontFamily: "'Libre Franklin', sans-serif",
    letterSpacing: "0.03em",
    transition: "all 0.3s cubic-bezier(0.23, 1, 0.32, 1)",
  },
  tabActive: {
    background: "var(--accent)",
    borderColor: "var(--accent)",
    color: "#f5efe7",
  },

  // Results
  resultsInfo: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    fontSize: 12,
    color: "var(--text-light)",
    fontWeight: 500,
  },
  clearSearch: {
    color: "var(--accent-warm)",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 600,
  },

  // Items Grid
  itemsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(175px, 1fr))",
    gap: 14,
  },
  itemCard: {
    background: "var(--surface)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(180, 160, 140, 0.12)",
    borderRadius: 20,
    overflow: "hidden",
    cursor: "pointer",
    transition: "all 0.45s cubic-bezier(0.23, 1, 0.32, 1)",
    position: "relative",
  },
  itemCardHover: {
    borderColor: "rgba(180, 160, 140, 0.25)",
    transform: "translateY(-5px)",
    boxShadow: "0 20px 40px rgba(180, 140, 100, 0.1), 0 8px 16px rgba(180, 140, 100, 0.05)",
  },
  itemCardSelected: {
    borderColor: "var(--accent-warm)",
    boxShadow: "0 0 0 1.5px var(--accent-warm), 0 12px 32px rgba(160, 103, 75, 0.12)",
  },
  itemImageWrap: {
    width: "100%",
    aspectRatio: "1",
    background: "linear-gradient(145deg, rgba(212, 163, 115, 0.06), rgba(201, 166, 144, 0.03))",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    overflow: "hidden",
  },
  itemImagePlaceholder: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  checkBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 26,
    height: 26,
    borderRadius: "50%",
    background: "var(--accent)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 2px 8px rgba(74, 55, 40, 0.2)",
  },
  itemInfo: {
    padding: "12px 14px 14px",
  },
  itemName: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text)",
    marginBottom: 4,
    lineHeight: 1.3,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  itemMeta: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  itemType: {
    fontSize: 11,
    color: "var(--text-light)",
    fontWeight: 500,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
  },
  itemPrice: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 14,
    fontWeight: 700,
    color: "var(--robux)",
  },
  robuxIcon: {
    fontSize: 12,
    opacity: 0.75,
  },
  robuxIconLg: {
    fontSize: 14,
    opacity: 0.8,
    color: "var(--robux)",
  },

  // Outfit Panel
  outfitPanel: {
    width: 320,
    background: "var(--surface)",
    borderLeft: "1px solid var(--border)",
    padding: "24px 20px",
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
  },
  outfitHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  outfitTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: "-0.01em",
    color: "var(--text)",
  },
  itemCount: {
    fontSize: 11,
    color: "var(--text-light)",
    background: "var(--surface-2)",
    padding: "4px 10px",
    borderRadius: 12,
    fontWeight: 600,
  },

  // Slots
  slotsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 8,
    marginBottom: 20,
    flex: 1,
  },
  outfitSlotEmpty: {
    background: "var(--surface-2)",
    border: "1.5px dashed rgba(180, 160, 140, 0.2)",
    borderRadius: 16,
    padding: 12,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 96,
  },
  outfitSlotFilled: {
    background: "var(--surface-2)",
    borderWidth: 1.5,
    borderStyle: "solid",
    borderColor: "rgba(180, 160, 140, 0.15)",
    borderRadius: 16,
    padding: 12,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    minHeight: 96,
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.23, 1, 0.32, 1)",
    position: "relative",
  },
  slotLabel: {
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: "0.15em",
    color: "var(--text-light)",
    textTransform: "uppercase",
  },
  slotPlaceholder: { opacity: 0.35 },
  slotItemThumb: {
    width: 38,
    height: 38,
    borderRadius: 12,
    background: "var(--surface-3)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  slotItemName: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 11,
    color: "var(--text)",
    textAlign: "center",
    lineHeight: 1.2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    maxWidth: "100%",
    fontWeight: 500,
  },
  removeX: {
    position: "absolute",
    top: 6,
    right: 6,
  },

  // Total
  totalRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 0",
    borderTop: "1px solid var(--border)",
    marginBottom: 16,
  },
  totalLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-muted)",
    letterSpacing: "0.02em",
  },
  totalValue: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 22,
    fontWeight: 700,
    color: "var(--robux)",
  },

  // Actions
  outfitActions: {
    display: "flex",
    gap: 8,
  },
  shareBtn: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "12px 18px",
    background: "var(--accent)",
    color: "#f5efe7",
    borderRadius: 24,
    fontWeight: 700,
    fontSize: 13,
    fontFamily: "'Libre Franklin', sans-serif",
    letterSpacing: "0.03em",
    transition: "all 0.3s cubic-bezier(0.23, 1, 0.32, 1)",
  },
  clearBtn: {
    padding: "12px 18px",
    background: "transparent",
    color: "var(--text-muted)",
    borderRadius: 24,
    fontWeight: 600,
    fontSize: 13,
    fontFamily: "'Libre Franklin', sans-serif",
    borderWidth: 1.5,
    borderStyle: "solid",
    borderColor: "rgba(180, 160, 140, 0.18)",
    letterSpacing: "0.03em",
    transition: "all 0.3s cubic-bezier(0.23, 1, 0.32, 1)",
  },

  // Info Banner
  infoBanner: {
    display: "flex",
    alignItems: "flex-start",
    margin: "0 28px 28px",
    padding: "14px 18px",
    background: "rgba(160, 103, 75, 0.06)",
    borderRadius: 16,
    border: "1px solid rgba(160, 103, 75, 0.1)",
    fontSize: 12,
    color: "var(--text-muted)",
    lineHeight: 1.6,
  },

  // Modal
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(74, 55, 40, 0.4)",
    backdropFilter: "blur(6px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
    animation: "fadeInUp 0.2s ease",
  },
  modal: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 24,
    padding: 32,
    width: 440,
    maxWidth: "90vw",
    animation: "slideIn 0.35s cubic-bezier(0.23, 1, 0.32, 1)",
    boxShadow: "0 32px 64px rgba(74, 55, 40, 0.12)",
  },
  modalTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 8,
    color: "var(--text)",
  },
  modalDesc: {
    color: "var(--text-muted)",
    fontSize: 13,
    marginBottom: 24,
    lineHeight: 1.6,
  },
  shareLinkRow: {
    display: "flex",
    gap: 8,
    marginBottom: 24,
  },
  shareCode: {
    flex: 1,
    padding: "12px 16px",
    background: "var(--surface-2)",
    borderRadius: 14,
    border: "1px solid var(--border)",
    color: "var(--accent-warm)",
    fontFamily: "'Libre Franklin', sans-serif",
    fontSize: 13,
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  copyBtn: {
    padding: "12px 22px",
    background: "var(--accent)",
    color: "#f5efe7",
    borderRadius: 14,
    fontWeight: 700,
    fontSize: 13,
    fontFamily: "'Libre Franklin', sans-serif",
    flexShrink: 0,
    letterSpacing: "0.03em",
  },
  outfitSummary: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 20,
  },
  summaryChip: {
    padding: "5px 12px",
    background: "var(--surface-2)",
    borderRadius: 12,
    fontSize: 11,
    color: "var(--text-muted)",
    border: "1px solid var(--border)",
    fontWeight: 500,
  },
  modalTotal: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 18,
    fontWeight: 700,
    color: "var(--text)",
    marginBottom: 24,
  },
  modalClose: {
    width: "100%",
    padding: "13px",
    background: "var(--surface-2)",
    color: "var(--text)",
    borderRadius: 16,
    fontWeight: 600,
    fontSize: 14,
    fontFamily: "'Libre Franklin', sans-serif",
    border: "1px solid var(--border)",
    letterSpacing: "0.02em",
    transition: "all 0.2s ease",
  },

  // Toast
  toast: {
    position: "fixed",
    bottom: 28,
    left: "50%",
    transform: "translateX(-50%)",
    background: "var(--surface)",
    border: "1.5px solid var(--accent-warm)",
    color: "var(--accent-warm)",
    padding: "11px 28px",
    borderRadius: 24,
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "'Libre Franklin', sans-serif",
    boxShadow: "0 12px 40px rgba(74, 55, 40, 0.12), 0 4px 12px rgba(74, 55, 40, 0.06)",
    zIndex: 200,
    animation: "toastIn 0.35s cubic-bezier(0.23, 1, 0.32, 1)",
    letterSpacing: "0.02em",
  },

  // Empty
  emptyState: {
    gridColumn: "1 / -1",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: 60,
  },
};
