export const styles = {
  root: {
    fontFamily: "'DM Sans', sans-serif",
    color: "var(--text)",
    background: "var(--bg)",
    minHeight: "100vh",
    position: "relative",
  },

  // Header
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 24px",
    borderBottom: "1px solid var(--border)",
    background: "var(--surface)",
  },
  logoRow: { display: "flex", alignItems: "center", gap: 16 },
  logo: { display: "flex", alignItems: "center", gap: 8 },
  logoIcon: {
    color: "var(--accent)",
    fontSize: 22,
    fontWeight: 700,
    filter: "drop-shadow(0 0 8px var(--accent-glow))",
  },
  logoText: {
    fontFamily: "'Space Mono', monospace",
    fontWeight: 700,
    fontSize: 18,
    letterSpacing: 3,
    color: "var(--text)",
  },
  tagline: {
    fontSize: 13,
    color: "var(--text-muted)",
    borderLeft: "1px solid var(--border)",
    paddingLeft: 16,
  },
  headerRight: { display: "flex", alignItems: "center", gap: 12 },
  badge: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 2,
    color: "var(--accent)",
    background: "var(--accent-dim)",
    padding: "4px 10px",
    borderRadius: 4,
    border: "1px solid rgba(0,229,160,0.2)",
  },

  // Trending
  trendingBar: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "8px 24px",
    background: "var(--surface-2)",
    borderBottom: "1px solid var(--border)",
    overflow: "hidden",
    whiteSpace: "nowrap",
    fontSize: 12,
  },
  trendingLabel: {
    fontFamily: "'Space Mono', monospace",
    fontWeight: 700,
    fontSize: 10,
    letterSpacing: 2,
    color: "var(--accent)",
    flexShrink: 0,
  },
  trendingItem: { color: "var(--text-muted)" },
  trendingDot: { color: "var(--border)", fontSize: 16 },

  // Layout
  mainLayout: {
    display: "flex",
    gap: 0,
    minHeight: "calc(100vh - 130px)",
  },
  catalogPanel: {
    flex: 1,
    padding: "20px 24px",
    overflowY: "auto",
  },

  // Search
  searchWrapper: {
    position: "relative",
    marginBottom: 16,
  },
  searchInput: {
    width: "100%",
    padding: "12px 16px 12px 42px",
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    color: "var(--text)",
    fontSize: 14,
    fontFamily: "'DM Sans', sans-serif",
    transition: "border-color 0.2s",
  },

  // Tabs
  tabsRow: {
    display: "flex",
    gap: 6,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  tab: {
    padding: "6px 14px",
    borderRadius: 8,
    background: "var(--surface)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    color: "var(--text-muted)",
    fontSize: 12,
    fontWeight: 500,
    fontFamily: "'DM Sans', sans-serif",
    transition: "all 0.15s",
  },
  tabActive: {
    background: "var(--accent-dim)",
    borderColor: "var(--accent)",
    color: "var(--accent)",
  },

  // Results
  resultsInfo: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    fontSize: 12,
    color: "var(--text-muted)",
  },
  clearSearch: {
    color: "var(--accent)",
    cursor: "pointer",
    fontSize: 12,
  },

  // Items Grid
  itemsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))",
    gap: 12,
  },
  itemCard: {
    background: "var(--surface)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 12,
    overflow: "hidden",
    cursor: "pointer",
    transition: "all 0.2s",
    position: "relative",
  },
  itemCardHover: {
    borderColor: "var(--border-hover)",
    transform: "translateY(-2px)",
    boxShadow: "0 8px 24px rgba(0,0,0,0.3)",
  },
  itemCardSelected: {
    borderColor: "var(--accent)",
    boxShadow: "0 0 0 1px var(--accent), 0 0 20px var(--accent-glow)",
  },
  itemImageWrap: {
    width: "100%",
    aspectRatio: "1",
    background: "var(--surface-2)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  itemImagePlaceholder: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  checkBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    borderRadius: "50%",
    background: "var(--accent)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 2px 8px var(--accent-glow)",
  },
  itemInfo: {
    padding: "10px 12px",
  },
  itemName: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text)",
    marginBottom: 4,
    lineHeight: 1.3,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  itemMeta: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  itemType: {
    fontSize: 11,
    color: "var(--text-muted)",
  },
  itemPrice: {
    fontSize: 12,
    fontWeight: 700,
    color: "var(--robux)",
    fontFamily: "'Space Mono', monospace",
  },
  robuxIcon: {
    fontSize: 11,
    opacity: 0.8,
  },
  robuxIconLg: {
    fontSize: 14,
    opacity: 0.8,
    color: "var(--robux)",
  },

  // Outfit Panel
  outfitPanel: {
    width: 320,
    background: "var(--surface)",
    borderLeft: "1px solid var(--border)",
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
  },
  outfitHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  outfitTitle: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 16,
    fontWeight: 700,
    letterSpacing: 1,
  },
  itemCount: {
    fontSize: 12,
    color: "var(--text-muted)",
    background: "var(--surface-2)",
    padding: "3px 8px",
    borderRadius: 6,
  },

  // Slots
  slotsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 8,
    marginBottom: 20,
    flex: 1,
  },
  outfitSlotEmpty: {
    background: "var(--surface-2)",
    border: "1px dashed var(--border)",
    borderRadius: 10,
    padding: 12,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 90,
  },
  outfitSlotFilled: {
    background: "var(--surface-2)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 10,
    padding: 12,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    minHeight: 90,
    cursor: "pointer",
    transition: "border-color 0.15s",
    position: "relative",
  },
  slotLabel: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: 2,
    color: "var(--text-muted)",
    textTransform: "uppercase",
  },
  slotPlaceholder: { opacity: 0.5 },
  slotItemThumb: {
    width: 36,
    height: 36,
    borderRadius: 8,
    background: "var(--surface-3)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  slotItemName: {
    fontSize: 11,
    color: "var(--text)",
    textAlign: "center",
    lineHeight: 1.2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    maxWidth: "100%",
  },
  removeX: {
    position: "absolute",
    top: 6,
    right: 6,
  },

  // Total
  totalRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 0",
    borderTop: "1px solid var(--border)",
    marginBottom: 16,
  },
  totalLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-muted)",
  },
  totalValue: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 18,
    fontWeight: 700,
    color: "var(--robux)",
  },

  // Actions
  outfitActions: {
    display: "flex",
    gap: 8,
  },
  shareBtn: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "10px 16px",
    background: "var(--accent)",
    color: "var(--bg)",
    borderRadius: 10,
    fontWeight: 700,
    fontSize: 13,
    fontFamily: "'DM Sans', sans-serif",
    transition: "all 0.15s",
  },
  clearBtn: {
    padding: "10px 16px",
    background: "var(--surface-2)",
    color: "var(--text-muted)",
    borderRadius: 10,
    fontWeight: 500,
    fontSize: 13,
    fontFamily: "'DM Sans', sans-serif",
    border: "1px solid var(--border)",
    transition: "all 0.15s",
  },

  // Info Banner
  infoBanner: {
    display: "flex",
    alignItems: "flex-start",
    margin: "0 24px 24px",
    padding: "12px 16px",
    background: "var(--accent-dim)",
    borderRadius: 10,
    border: "1px solid rgba(0,229,160,0.15)",
    fontSize: 12,
    color: "var(--text-muted)",
    lineHeight: 1.5,
  },

  // Modal
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.7)",
    backdropFilter: "blur(4px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
    animation: "fadeInUp 0.2s ease",
  },
  modal: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 16,
    padding: 28,
    width: 420,
    maxWidth: "90vw",
    animation: "slideIn 0.25s ease",
  },
  modalTitle: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 20,
    fontWeight: 700,
    marginBottom: 8,
  },
  modalDesc: {
    color: "var(--text-muted)",
    fontSize: 13,
    marginBottom: 20,
    lineHeight: 1.5,
  },
  shareLinkRow: {
    display: "flex",
    gap: 8,
    marginBottom: 20,
  },
  shareCode: {
    flex: 1,
    padding: "10px 14px",
    background: "var(--surface-2)",
    borderRadius: 8,
    border: "1px solid var(--border)",
    color: "var(--accent)",
    fontFamily: "'Space Mono', monospace",
    fontSize: 13,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  copyBtn: {
    padding: "10px 20px",
    background: "var(--accent)",
    color: "var(--bg)",
    borderRadius: 8,
    fontWeight: 700,
    fontSize: 13,
    fontFamily: "'DM Sans', sans-serif",
    flexShrink: 0,
  },
  outfitSummary: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 16,
  },
  summaryChip: {
    padding: "4px 10px",
    background: "var(--surface-2)",
    borderRadius: 6,
    fontSize: 11,
    color: "var(--text-muted)",
    border: "1px solid var(--border)",
  },
  modalTotal: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 16,
    fontWeight: 700,
    color: "var(--text)",
    marginBottom: 20,
  },
  modalClose: {
    width: "100%",
    padding: "12px",
    background: "var(--surface-2)",
    color: "var(--text)",
    borderRadius: 10,
    fontWeight: 600,
    fontSize: 14,
    fontFamily: "'DM Sans', sans-serif",
    border: "1px solid var(--border)",
  },

  // Toast
  toast: {
    position: "fixed",
    bottom: 24,
    left: "50%",
    transform: "translateX(-50%)",
    background: "var(--surface-2)",
    border: "1px solid var(--accent)",
    color: "var(--accent)",
    padding: "10px 24px",
    borderRadius: 10,
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "'DM Sans', sans-serif",
    boxShadow: "0 8px 32px rgba(0,0,0,0.4), 0 0 20px var(--accent-glow)",
    zIndex: 200,
    animation: "toastIn 0.25s ease",
  },

  // Empty
  emptyState: {
    gridColumn: "1 / -1",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: 60,
  },
};
